version: '3.8'
services:
  web:
    image: nginx
    ports:
      - 9090:80
  database:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
